core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    
    # # Products detail page
    path('product/<pid>/', views.product_detail_view, name='product-detail'),
    path("ajax-contact-form", views.ajax_contact_form, name="ajax-contact-form"),
]

real_estate/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
# from core.views import serve_media
from real_estate.sitemaps import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("rosetta/", include("rosetta.urls")),
    path("user/", include("userauths.urls")),
    path("", include("core.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # re_path(r"^media/(?P<path>.*)$", serve_media),
    prefix_default_language=False,
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import strip_tags
from userauths.models import User
from ckeditor_uploader.fields import RichTextUploadingField

class Product(models.Model):
    pid = ShortUUIDField(unique=True,length=10,max_length=20,alphabet='abcdefgh12345')
    title = models.CharField(max_length=100)
    description = RichTextUploadingField(null=True,blank=True)
    mini_description = models.TextField(default=None, null=True, blank=True)
    status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True,blank=True)
    
    class Meta:
        verbose_name_plural = 'Products'
        
    def product_description(self):
        return strip_tags(self.description)
    product_description.short_description = "Description"

    def __str__(self) -> str:
        return self.title
    
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name="p_images")
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'Product Images'

class ContactUs(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self) -> str:
        return self.full_name
    
    class Meta:
        verbose_name = "ContactUs"
        verbose_name_plural = "ContactUs"

    def __str__(self) -> str:
        return self.email

core/views.py
import json
from django.shortcuts import render
from core.models import Product, ContactUs
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings

# Create your views here.
def index(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'core/index.html',context)

def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    p_image = product.p_images.all()
    context = {
        'product': product,
        'p_image': p_image,
    }
    return render(request, 'core/product-detail.html',context)

def ajax_contact_form(request):
    full_name = request.GET.get("full_name")
    email = request.GET.get("email")
    phone = request.GET.get("phone")
    message = request.GET.get("message")
    
    from_email = settings.DEFAULT_FROM_EMAIL
    contact, _ = ContactUs.objects.get_or_create(full_name=full_name, email=email, phone=phone, message=message)
    context = {
        "full_name": full_name,
        "email": email,
        "phone": phone,
        "message": message
    }
    email_template = "emails/contact_email_template.html"
    message = render_to_string(email_template, context)
    subject = "Có khách hàng mới quan tâm dự án của bạn"
    to_email = settings.ADMIN_EMAIL
    mail = EmailMessage(subject, message, from_email, to=[to_email])
    mail.send()
    
    return JsonResponse({
        "success": True,
        "message": " Message sent successfully."
    })

templates/core/product-detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}
{% block meta_header %}
    <title>The Oasis Riverside</title>
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
    <meta property="og:title" content="The Oasis Riverside" />
    <meta property="og:description" content="The Oasis Riverside – dự án bất động sản ven sông mang đến không gian sống xanh, tiện ích hiện đại và vị trí chiến lược. Khám phá căn hộ cao cấp, thiết kế tinh tế, môi trường trong lành và tiềm năng sinh lời bền vững." />
    <meta property="og:url" content="https://duantheoasisriverside.com/" />
    <meta property="og:image" content="{% static 'assets/img/logo/logo.png' %}" />
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="vi_VN" />
    <meta property="og:site_name" content="The Oasis Riverside" />
{% endblock meta_header %}
{% block content %}
<!-- Start Property Details Area -->
    <div class="property-details-area ptb-120 quicksand-font-family">
        <div class="container-fluid">
            <div class="row justify-content-center g-4">
                <div class="col-xl-6 col-md-12">
                    <div class="property-details-image-tabs">
                        <div class="tab-content" id="myTabContent">
                            {% for p in p_image %}
                            <div class="tab-pane fade show {% if forloop.first %}active{% endif %}" id="imgdt{{ p.id }}" role="tabpanel">
                                <img src="{{ p.images.url }}" alt="image">
                            </div>
                            {% endfor %}
                        </div>
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            {% for p in p_image %}
                            <li class="nav-item">
                                <a class="nav-link {% if forloop.first %}active{% endif %}" id="imgdt{{ p.id }}-tab" data-bs-toggle="tab" href="#imgdt{{ p.id }}" role="tab" aria-controls="imgdt{{ p.id }}">
                                    <img src="{{ p.images.url }}" alt="image">
                                </a>
                            </li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                </div>
                <div class="col-xl-6 col-md-12">
                    <div class="property-details-desc">
                        <h2>{{ product.title }}</h2>
                        <div class="content">
                            {{ product.description|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- End Property Details Area -->
{% endblock content %}

templates/core/product-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}
{% block meta_header %}
    <title>The Oasis Riverside</title>
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
    <meta property="og:title" content="The Oasis Riverside" />
    <meta property="og:description" content="The Oasis Riverside – dự án bất động sản ven sông mang đến không gian sống xanh, tiện ích hiện đại và vị trí chiến lược. Khám phá căn hộ cao cấp, thiết kế tinh tế, môi trường trong lành và tiềm năng sinh lời bền vững." />
    <meta property="og:url" content="https://duantheoasisriverside.com/" />
    <meta property="og:image" content="{% static 'assets/img/logo/logo.png' %}" />
    <meta property="og:type" content="website" />
    <meta property="og:locale" content="vi_VN" />
    <meta property="og:site_name" content="The Oasis Riverside" />
{% endblock meta_header %}
{% block content %}
    <!-- Breadcrumb -->
    <section class="section-breadcrumb margin-b-50">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row bb-breadcrumb-inner">
                        <div class="col-md-12 col-sm-12"></div>
                            <ul class="bb-breadcrumb-list">
                                <li class="bb-breadcrumb-item"><a href="{% url 'core:index' %}">{% trans 'Trang chủ' %}</a></li>
                                <li><i class="ri-arrow-right-double-fill"></i></li>
                                <li class="bb-breadcrumb-item active">{% trans 'Dự án' %}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Shop section -->
    <section class="section-shop padding-b-50">
        <div class="container">
            <div class="row">
                <div class="bb-shop-overlay"></div>
                <div class="col-12">
                    <div class="bb-shop-pro-inner">
                        <div class="row mb-minus-24">
                            <div class="col-12">
                                <div class="bb-pro-list-top">
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="bb-bl-btn">
                                                <!-- <button type="button" class="grid-btn btn-filter">
                                                    <i class="ri-equalizer-2-line"></i>
                                                </button> -->
                                                <button type="button" class="grid-btn btn-grid-100 active">
                                                    <i class="ri-apps-line"></i>
                                                </button>
                                                <button type="button" class="grid-btn btn-list-100">
                                                    <i class="ri-list-unordered"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% for p in products %}
                            <div class="col-lg-3 col-md-4 col-6 mb-24 bb-product-box pro-bb-content" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200">
                                <div class="bb-pro-box">
                                    <div class="bb-pro-img">
                                        <a href="{% url 'core:product-detail' p.pid %}">
                                            <div class="inner-img">
                                                <img class="main-img" src="{{ p.image.url }}"
                                                    alt="product-1">
                                                <img class="hover-img" src="{{ p.image.url }}"
                                                    alt="product-1">
                                            </div>
                                        </a>
                                    </div>
                                    <div class="bb-pro-contact">
                                        <h4 class="bb-pro-title"><a href="{% url 'core:product-detail' p.pid %}">{{ p.title }}</a>
                                        </h4>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}